const fileInput=document.getElementById("fileInput"),dropZone=document.getElementById("dropZone"),canvas=document.getElementById("canvas"),ctx=canvas.getContext("2d"),amount=document.getElementById("amount"),size=document.getElementById("size"),amountValue=document.getElementById("amountValue"),sizeValue=document.getElementById("sizeValue"),download=document.getElementById("download"),reset=document.getElementById("reset"),placeholder=document.getElementById("placeholder"),fileName=document.getElementById("fileName");
let image=null,url=null;
const bayer=[[0,8,2,10],[12,4,14,6],[3,11,1,9],[15,7,13,5]];
function render(){if(!image)return;const w=Math.min(image.naturalWidth,1400),h=Math.round(image.naturalHeight*(w/image.naturalWidth));canvas.width=w;canvas.height=h;ctx.drawImage(image,0,0,w,h);const d=ctx.getImageData(0,0,w,h),a=d.data,str=+amount.value/100,s=+size.value;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,t=(bayer[y%s][x%s]/(s*s)-.5)*255*str;for(let c=0;c<3;c++){const v=Math.max(0,Math.min(255,a[i+c]+t));a[i+c]=v<128?0:255}}ctx.putImageData(d,0,0);amountValue.textContent=amount.value+"%";sizeValue.textContent=size.value+"×"+size.value;placeholder.hidden=true;canvas.hidden=false;download.disabled=false;reset.disabled=false}
function load(file){if(!file||!file.type.startsWith("image/"))return;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(file);const img=new Image();img.onload=()=>{image=img;fileName.textContent=file.name+" · Procesado en tu navegador.";render()};img.src=url}
fileInput.onchange=()=>load(fileInput.files[0]);amount.oninput=render;size.oninput=render;
["dragenter","dragover"].forEach(e=>dropZone.addEventListener(e,x=>{x.preventDefault();dropZone.classList.add("dragging")}));["dragleave","drop"].forEach(e=>dropZone.addEventListener(e,x=>{x.preventDefault();dropZone.classList.remove("dragging")}));dropZone.onclick=e=>{if(e.target!==fileInput)fileInput.click()};dropZone.ondrop=e=>load(e.dataTransfer.files[0]);
download.onclick=()=>{const a=document.createElement("a");a.download="dithering.png";a.href=canvas.toDataURL("image/png");a.click()};
reset.onclick=()=>{image=null;fileInput.value="";canvas.hidden=true;placeholder.hidden=false;download.disabled=true;reset.disabled=true;fileName.textContent="Ninguna imagen seleccionada · Procesado en tu navegador."};
